### ISSUE TITLE
Migrations are not run on startup

### ISSUE THREAD

**Issue by lnicola** [richardbrodie/hermes#2]
The usage instructions don't mention anything about the database, and the application doesn't run the migration scripts, so startup fails.

**Comment by richardbrodie** [comment]
Fixed in f1fcf57a6e8247a8a41129a397b7ee66a5e572eb

**Comment by lnicola** [comment]
I think you can use https://docs.rs/diesel_migrations/*/diesel_migrations/macro.embed_migrations.html to avoid installing `diesel-cli`.

**Comment by richardbrodie** [comment]
Interesting, when I originally wrote the migrations I wanted to do something like this (I come from a rails background) but I remember there was some reason why I didn't. I don't, however, remember what that reason was.

But yeah, this way seems better.

**Comment by lnicola** [comment]
I haven't really used `diesel`'s support for migrations, so I can't say either. :smile:
